---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: app
  namespace: 
spec:
  template:
    spec:
      containers:
        - image: REGISTRY_URL//app:BUILD_NUMBER
          ports:
            - containerPort: 3000
